import type { Metadata } from "next";
import { CustomerDetail } from "@/features/customers/components/customer-detail";

export const metadata: Metadata = {
  title: "Customer",
};

/**
 * One customer (brief §6.6, design canvas artboard `2h`).
 *
 * Stays a Server Component that does exactly one thing: await the route param
 * and hand the id down. Everything on the screen is a query — the customer and
 * their debt summary, the organization's currency and timezone, the caller's
 * permissions — so the client boundary starts at `<CustomerDetail>`.
 *
 * `params` is a **Promise** in this version of Next; awaiting it is not
 * optional (`node_modules/next/dist/docs/01-app/01-getting-started/03-layouts-and-pages.md:216-232`).
 * It is typed by hand rather than through the global `PageProps<'/customers/[id]'>`
 * helper because that type is generated by `next dev` / `next build` /
 * `next typegen` into `.next/types/routes.d.ts`, which currently knows only the
 * Slice 1 routes — a typecheck run before the next build would fail on a route
 * literal that does not exist yet.
 *
 * The title is static. A per-customer `generateMetadata` would need the
 * customer's name, which means a server-side fetch carrying the session
 * cookie; nothing in this app fetches from the server, and the tab title is
 * not worth being the first thing that does.
 *
 * No route entry was needed: `resolveRoutePermission` matches the longest
 * guarded prefix on a `/` boundary, so `/customers/<id>` inherits
 * `customers:view` from `/customers` in `ROUTE_PERMISSIONS`.
 */
export default async function Customer({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;

  return <CustomerDetail customerId={id} />;
}
