import type { Metadata } from "next";
import { PublicLinkUnavailable } from "@/features/projects/components/public-link-unavailable";
import { PublicProjectView } from "@/features/projects/components/public-project-view";
import { fetchPublicProject } from "@/features/projects/services/public-project.service";

/**
 * The client-facing share page — design canvas artboard `2l`, the right-hand
 * panel.
 *
 * **This page must NOT call `requirePageAccess()`, and that is the single most
 * important thing about it.** It sits outside the `(app)` route group on
 * purpose: no shell, no sidebar, no session, no organization. Its reader is a
 * client of the business who has been sent a link — they have no account here
 * and never will, and a redirect to `/login` would be the product asking a
 * stranger to sign in to read their own job.
 *
 * The exclusion is real at three levels and was confirmed rather than assumed:
 *
 *   1. **`proxy.ts` excludes `/p/`** in its matcher literal — `"/((?!api/|
 *      _next/static|_next/image|p/|favicon.ico|.*\\.[\\w]+$).*)"` — so an
 *      anonymous request never reaches the cookie check that bounces the rest
 *      of the app to `/login`.
 *   2. **`app/(app)/layout.tsx` is the real server-side gate**, and this route
 *      is not under it. The layout that does wrap this page is the root one,
 *      which renders fonts and providers and reads no session.
 *   3. **Nothing here is in `ROUTE_PERMISSIONS`.** `/p/:token` has no
 *      permission because it has no member.
 *
 * **One server-side read, and every failure is the same answer.** A missing,
 * malformed, unpublished, regenerated or deleted token — and a rate limit, and
 * a backend that is down — all render `<PublicLinkUnavailable />`. The service
 * never throws and never distinguishes, because the API deliberately does not
 * either: a token over 128 characters answers **422** rather than 404
 * (contract §3.7), so branching on status would be both wrong and an oracle.
 *
 * `dynamic = "force-dynamic"` because this must never be cached or statically
 * rendered: an unpublish takes effect on the API instantly (the public lookup
 * filters on `isPublished: true` with no grace period), and a cached page would
 * keep serving a project whose owner has just revoked it. The API's own
 * response carries `Cache-Control: no-store` for the same reason
 * (`public.controller.ts:16-17`).
 */
export const dynamic = "force-dynamic";

/**
 * **`noindex, nofollow`, and it is not optional.**
 *
 * A share token is a bearer credential — anyone holding the URL can read the
 * project. If a client pastes the link into a page a crawler can reach, or an
 * email client prefetches it, an indexed copy would put a business's private
 * job into a search result with no way to take it back except regenerating the
 * link, which breaks it for the client too. `nocache` and `noarchive` cover the
 * cached-copy case for the engines that honour them.
 *
 * The title is generic on purpose: a per-project title would leak the project's
 * name into a browser history entry, a tab bar in a screen share, and any link
 * preview generated by whatever the link was pasted into.
 */
export const metadata: Metadata = {
  title: "Project",
  robots: {
    index: false,
    follow: false,
    nocache: true,
    noarchive: true,
  },
};

export default async function PublicProjectPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  // `params` is a Promise in this version of Next; awaiting it is not optional.
  // Typed by hand rather than through the generated `PageProps<'/p/[token]'>`
  // helper, which only exists after a build has written `.next/types`.
  const { token } = await params;

  const data = await fetchPublicProject(token);
  if (!data) return <PublicLinkUnavailable />;

  return <PublicProjectView data={data} />;
}
